/*
 Navicat Premium Data Transfer

 Source Server         : 司法云Oracle
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : 47.101.204.102:1521
 Source Schema         : TEST

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 04/08/2020 14:35:28
*/


-- ----------------------------
-- Table structure for XXL_JOB_GROUP
-- ----------------------------
DROP TABLE "TEST"."XXL_JOB_GROUP";
CREATE TABLE "TEST"."XXL_JOB_GROUP" (
  "ID" NUMBER(11) NOT NULL ,
  "APP_NAME" NVARCHAR2(64) NOT NULL ,
  "TITLE" NVARCHAR2(12) NOT NULL ,
  "ADDRESS_TYPE" NUMBER(4) NOT NULL ,
  "ADDRESS_LIST" NVARCHAR2(512) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "TEST"."XXL_JOB_GROUP"."APP_NAME" IS '执行器AppName';
COMMENT ON COLUMN "TEST"."XXL_JOB_GROUP"."TITLE" IS '执行器名称';
COMMENT ON COLUMN "TEST"."XXL_JOB_GROUP"."ADDRESS_TYPE" IS '执行器地址类型：0=自动注册、1=手动录入';
COMMENT ON COLUMN "TEST"."XXL_JOB_GROUP"."ADDRESS_LIST" IS '执行器地址列表，多地址逗号分隔';

-- ----------------------------
-- Records of XXL_JOB_GROUP
-- ----------------------------
INSERT INTO "TEST"."XXL_JOB_GROUP" VALUES ('1', 'xxl-job-executor-sample', '示例执行器', '0', 'http://127.0.0.1:9999/');

-- ----------------------------
-- Table structure for XXL_JOB_INFO
-- ----------------------------
DROP TABLE "TEST"."XXL_JOB_INFO";
CREATE TABLE "TEST"."XXL_JOB_INFO" (
  "ID" NUMBER(11) NOT NULL ,
  "JOB_GROUP" NUMBER(11) NOT NULL ,
  "JOB_CRON" NVARCHAR2(128) NOT NULL ,
  "JOB_DESC" NVARCHAR2(255) NOT NULL ,
  "ADD_TIME" DATE ,
  "UPDATE_TIME" DATE ,
  "AUTHOR" NVARCHAR2(64) ,
  "ALARM_EMAIL" NVARCHAR2(255) ,
  "EXECUTOR_ROUTE_STRATEGY" NVARCHAR2(50) ,
  "EXECUTOR_HANDLER" NVARCHAR2(255) ,
  "EXECUTOR_PARAM" NVARCHAR2(512) ,
  "EXECUTOR_BLOCK_STRATEGY" NVARCHAR2(50) ,
  "EXECUTOR_TIMEOUT" NUMBER(11) NOT NULL ,
  "EXECUTOR_FAIL_RETRY_COUNT" NUMBER(11) NOT NULL ,
  "GLUE_TYPE" NVARCHAR2(50) NOT NULL ,
  "GLUE_SOURCE" NCLOB ,
  "GLUE_REMARK" NVARCHAR2(128) ,
  "GLUE_UPDATETIME" DATE ,
  "CHILD_JOBID" NVARCHAR2(255) ,
  "TRIGGER_STATUS" NUMBER(4) NOT NULL ,
  "TRIGGER_LAST_TIME" NUMBER(20) NOT NULL ,
  "TRIGGER_NEXT_TIME" NUMBER(20) NOT NULL 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "TEST"."XXL_JOB_INFO"."JOB_GROUP" IS '执行器主键ID';
COMMENT ON COLUMN "TEST"."XXL_JOB_INFO"."JOB_CRON" IS '任务执行CRON';
COMMENT ON COLUMN "TEST"."XXL_JOB_INFO"."AUTHOR" IS '作者';
COMMENT ON COLUMN "TEST"."XXL_JOB_INFO"."ALARM_EMAIL" IS '报警邮件';
COMMENT ON COLUMN "TEST"."XXL_JOB_INFO"."EXECUTOR_ROUTE_STRATEGY" IS '执行器路由策略';
COMMENT ON COLUMN "TEST"."XXL_JOB_INFO"."EXECUTOR_HANDLER" IS '执行器任务handler';
COMMENT ON COLUMN "TEST"."XXL_JOB_INFO"."EXECUTOR_PARAM" IS '执行器任务参数';
COMMENT ON COLUMN "TEST"."XXL_JOB_INFO"."EXECUTOR_BLOCK_STRATEGY" IS '阻塞处理策略';
COMMENT ON COLUMN "TEST"."XXL_JOB_INFO"."EXECUTOR_TIMEOUT" IS '任务执行超时时间，单位秒';
COMMENT ON COLUMN "TEST"."XXL_JOB_INFO"."EXECUTOR_FAIL_RETRY_COUNT" IS '失败重试次数';
COMMENT ON COLUMN "TEST"."XXL_JOB_INFO"."GLUE_TYPE" IS 'GLUE类型';
COMMENT ON COLUMN "TEST"."XXL_JOB_INFO"."GLUE_SOURCE" IS 'GLUE源代码';
COMMENT ON COLUMN "TEST"."XXL_JOB_INFO"."GLUE_REMARK" IS 'GLUE备注';
COMMENT ON COLUMN "TEST"."XXL_JOB_INFO"."GLUE_UPDATETIME" IS 'GLUE更新时间';
COMMENT ON COLUMN "TEST"."XXL_JOB_INFO"."CHILD_JOBID" IS '子任务ID，多个逗号分隔';
COMMENT ON COLUMN "TEST"."XXL_JOB_INFO"."TRIGGER_STATUS" IS '调度状态：0-停止，1-运行';
COMMENT ON COLUMN "TEST"."XXL_JOB_INFO"."TRIGGER_LAST_TIME" IS '上次调度时间';
COMMENT ON COLUMN "TEST"."XXL_JOB_INFO"."TRIGGER_NEXT_TIME" IS '下次调度时间';

-- ----------------------------
-- Records of XXL_JOB_INFO
-- ----------------------------
INSERT INTO "TEST"."XXL_JOB_INFO" VALUES ('1', '1', '0 0 0 * * ? *', '测试任务1', TO_DATE('2018-11-03 22:21:31', 'SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-08-03 18:40:02', 'SYYYY-MM-DD HH24:MI:SS'), 'XXL', NULL, 'FIRST', 'demoJobHandler2', NULL, 'SERIAL_EXECUTION', '0', '0', 'BEAN', NULL, 'GLUE代码初始化', TO_DATE('2018-11-03 22:21:31', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '0', '0', '0');

-- ----------------------------
-- Table structure for XXL_JOB_LOCK
-- ----------------------------
DROP TABLE "TEST"."XXL_JOB_LOCK";
CREATE TABLE "TEST"."XXL_JOB_LOCK" (
  "LOCK_NAME" NVARCHAR2(50) NOT NULL 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "TEST"."XXL_JOB_LOCK"."LOCK_NAME" IS '锁名称';

-- ----------------------------
-- Records of XXL_JOB_LOCK
-- ----------------------------
INSERT INTO "TEST"."XXL_JOB_LOCK" VALUES ('schedule_lock');

-- ----------------------------
-- Table structure for XXL_JOB_LOG
-- ----------------------------
DROP TABLE "TEST"."XXL_JOB_LOG";
CREATE TABLE "TEST"."XXL_JOB_LOG" (
  "ID" NUMBER(20) NOT NULL ,
  "JOB_GROUP" NUMBER(11) NOT NULL ,
  "JOB_ID" NUMBER(11) NOT NULL ,
  "EXECUTOR_ADDRESS" NVARCHAR2(255) ,
  "EXECUTOR_HANDLER" NVARCHAR2(255) ,
  "EXECUTOR_PARAM" NVARCHAR2(512) ,
  "EXECUTOR_SHARDING_PARAM" NVARCHAR2(20) ,
  "EXECUTOR_FAIL_RETRY_COUNT" NUMBER(11) NOT NULL ,
  "TRIGGER_TIME" DATE ,
  "TRIGGER_CODE" NUMBER(11) NOT NULL ,
  "TRIGGER_MSG" NCLOB ,
  "HANDLE_TIME" DATE ,
  "HANDLE_CODE" NUMBER(11) NOT NULL ,
  "HANDLE_MSG" NCLOB ,
  "ALARM_STATUS" NUMBER(4) NOT NULL 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "TEST"."XXL_JOB_LOG"."JOB_GROUP" IS '执行器主键ID';
COMMENT ON COLUMN "TEST"."XXL_JOB_LOG"."JOB_ID" IS '任务，主键ID';
COMMENT ON COLUMN "TEST"."XXL_JOB_LOG"."EXECUTOR_ADDRESS" IS '执行器地址，本次执行的地址';
COMMENT ON COLUMN "TEST"."XXL_JOB_LOG"."EXECUTOR_HANDLER" IS '执行器任务handler';
COMMENT ON COLUMN "TEST"."XXL_JOB_LOG"."EXECUTOR_PARAM" IS '执行器任务参数';
COMMENT ON COLUMN "TEST"."XXL_JOB_LOG"."EXECUTOR_SHARDING_PARAM" IS '执行器任务分片参数，格式如 1/2';
COMMENT ON COLUMN "TEST"."XXL_JOB_LOG"."EXECUTOR_FAIL_RETRY_COUNT" IS '失败重试次数';
COMMENT ON COLUMN "TEST"."XXL_JOB_LOG"."TRIGGER_TIME" IS '调度-时间';
COMMENT ON COLUMN "TEST"."XXL_JOB_LOG"."TRIGGER_CODE" IS '调度-结果';
COMMENT ON COLUMN "TEST"."XXL_JOB_LOG"."TRIGGER_MSG" IS '调度-日志';
COMMENT ON COLUMN "TEST"."XXL_JOB_LOG"."HANDLE_TIME" IS '执行-时间';
COMMENT ON COLUMN "TEST"."XXL_JOB_LOG"."HANDLE_CODE" IS '执行-状态';
COMMENT ON COLUMN "TEST"."XXL_JOB_LOG"."HANDLE_MSG" IS '执行-日志';
COMMENT ON COLUMN "TEST"."XXL_JOB_LOG"."ALARM_STATUS" IS '告警状态：0-默认、1-无需告警、2-告警成功、3-告警失败';

-- ----------------------------
-- Records of XXL_JOB_LOG
-- ----------------------------
INSERT INTO "TEST"."XXL_JOB_LOG" VALUES ('27', '1', '1', 'http://127.0.0.1:9999/', 'demoJobHandler2', NULL, NULL, '0', TO_DATE('2020-08-03 18:42:23', 'SYYYY-MM-DD HH24:MI:SS'), '200', '任务触发类型：手动触发<br>调度机器：192.168.56.1<br>执行器-注册方式：自动注册<br>执行器-地址列表：[http://127.0.0.1:9999/]<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>触发调度：<br>address：http://127.0.0.1:9999/<br>code：200<br>msg：null', TO_DATE('2020-08-03 18:42:29', 'SYYYY-MM-DD HH24:MI:SS'), '200', NULL, '0');
INSERT INTO "TEST"."XXL_JOB_LOG" VALUES ('41', '1', '1', 'http://127.0.0.1:9999/', 'demoJobHandler2', NULL, NULL, '0', TO_DATE('2020-08-04 13:45:35', 'SYYYY-MM-DD HH24:MI:SS'), '200', '任务触发类型：手动触发<br>调度机器：192.168.56.1<br>执行器-注册方式：自动注册<br>执行器-地址列表：[http://127.0.0.1:9999/]<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>触发调度：<br>address：http://127.0.0.1:9999/<br>code：200<br>msg：null', TO_DATE('2020-08-04 13:45:42', 'SYYYY-MM-DD HH24:MI:SS'), '200', NULL, '0');

-- ----------------------------
-- Table structure for XXL_JOB_LOG_REPORT
-- ----------------------------
DROP TABLE "TEST"."XXL_JOB_LOG_REPORT";
CREATE TABLE "TEST"."XXL_JOB_LOG_REPORT" (
  "ID" NUMBER(11) NOT NULL ,
  "TRIGGER_DAY" DATE ,
  "RUNNING_COUNT" NUMBER(11) NOT NULL ,
  "SUC_COUNT" NUMBER(11) NOT NULL ,
  "FAIL_COUNT" NUMBER(11) NOT NULL 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "TEST"."XXL_JOB_LOG_REPORT"."TRIGGER_DAY" IS '调度-时间';
COMMENT ON COLUMN "TEST"."XXL_JOB_LOG_REPORT"."RUNNING_COUNT" IS '运行中-日志数量';
COMMENT ON COLUMN "TEST"."XXL_JOB_LOG_REPORT"."SUC_COUNT" IS '执行成功-日志数量';
COMMENT ON COLUMN "TEST"."XXL_JOB_LOG_REPORT"."FAIL_COUNT" IS '执行失败-日志数量';

-- ----------------------------
-- Records of XXL_JOB_LOG_REPORT
-- ----------------------------
INSERT INTO "TEST"."XXL_JOB_LOG_REPORT" VALUES ('16', TO_DATE('2020-08-03 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '0', '1', '0');
INSERT INTO "TEST"."XXL_JOB_LOG_REPORT" VALUES ('17', TO_DATE('2020-08-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '0', '0', '0');
INSERT INTO "TEST"."XXL_JOB_LOG_REPORT" VALUES ('18', TO_DATE('2020-08-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '0', '0', '0');
INSERT INTO "TEST"."XXL_JOB_LOG_REPORT" VALUES ('21', TO_DATE('2020-08-04 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '0', '1', '0');

-- ----------------------------
-- Table structure for XXL_JOB_LOGGLUE
-- ----------------------------
DROP TABLE "TEST"."XXL_JOB_LOGGLUE";
CREATE TABLE "TEST"."XXL_JOB_LOGGLUE" (
  "ID" NUMBER(11) NOT NULL ,
  "JOB_ID" NUMBER(11) NOT NULL ,
  "GLUE_TYPE" NVARCHAR2(50) ,
  "GLUE_SOURCE" NCLOB ,
  "GLUE_REMARK" NVARCHAR2(128) NOT NULL ,
  "ADD_TIME" DATE ,
  "UPDATE_TIME" DATE 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "TEST"."XXL_JOB_LOGGLUE"."JOB_ID" IS '任务，主键ID';
COMMENT ON COLUMN "TEST"."XXL_JOB_LOGGLUE"."GLUE_TYPE" IS 'GLUE类型';
COMMENT ON COLUMN "TEST"."XXL_JOB_LOGGLUE"."GLUE_SOURCE" IS 'GLUE源代码';
COMMENT ON COLUMN "TEST"."XXL_JOB_LOGGLUE"."GLUE_REMARK" IS 'GLUE备注';

-- ----------------------------
-- Table structure for XXL_JOB_REGISTRY
-- ----------------------------
DROP TABLE "TEST"."XXL_JOB_REGISTRY";
CREATE TABLE "TEST"."XXL_JOB_REGISTRY" (
  "ID" NUMBER(11) NOT NULL ,
  "REGISTRY_GROUP" NVARCHAR2(50) NOT NULL ,
  "REGISTRY_KEY" NVARCHAR2(255) NOT NULL ,
  "REGISTRY_VALUE" NVARCHAR2(255) NOT NULL ,
  "UPDATE_TIME" DATE 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for XXL_JOB_USER
-- ----------------------------
DROP TABLE "TEST"."XXL_JOB_USER";
CREATE TABLE "TEST"."XXL_JOB_USER" (
  "ID" NUMBER(11) NOT NULL ,
  "USERNAME" NVARCHAR2(50) NOT NULL ,
  "PASSWORD" NVARCHAR2(50) NOT NULL ,
  "ROLE" NUMBER(4) NOT NULL ,
  "PERMISSION" NVARCHAR2(255) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "TEST"."XXL_JOB_USER"."USERNAME" IS '账号';
COMMENT ON COLUMN "TEST"."XXL_JOB_USER"."PASSWORD" IS '密码';
COMMENT ON COLUMN "TEST"."XXL_JOB_USER"."ROLE" IS '角色：0-普通用户、1-管理员';
COMMENT ON COLUMN "TEST"."XXL_JOB_USER"."PERMISSION" IS '权限：执行器ID列表，多个逗号分割';

-- ----------------------------
-- Records of XXL_JOB_USER
-- ----------------------------
INSERT INTO "TEST"."XXL_JOB_USER" VALUES ('1', 'admin', 'e10adc3949ba59abbe56e057f20f883e', '1', NULL);

-- ----------------------------
-- Primary Key structure for table XXL_JOB_GROUP
-- ----------------------------
ALTER TABLE "TEST"."XXL_JOB_GROUP" ADD CONSTRAINT "SYS_C0014513" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table XXL_JOB_GROUP
-- ----------------------------
ALTER TABLE "TEST"."XXL_JOB_GROUP" ADD CONSTRAINT "SYS_C0014476" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_GROUP" ADD CONSTRAINT "SYS_C0014477" CHECK ("APP_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_GROUP" ADD CONSTRAINT "SYS_C0014478" CHECK ("TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_GROUP" ADD CONSTRAINT "SYS_C0014479" CHECK ("ADDRESS_TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table XXL_JOB_INFO
-- ----------------------------
ALTER TABLE "TEST"."XXL_JOB_INFO" ADD CONSTRAINT "SYS_C0014514" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table XXL_JOB_INFO
-- ----------------------------
ALTER TABLE "TEST"."XXL_JOB_INFO" ADD CONSTRAINT "SYS_C0014480" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_INFO" ADD CONSTRAINT "SYS_C0014481" CHECK ("JOB_GROUP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_INFO" ADD CONSTRAINT "SYS_C0014482" CHECK ("JOB_CRON" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_INFO" ADD CONSTRAINT "SYS_C0014483" CHECK ("JOB_DESC" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_INFO" ADD CONSTRAINT "SYS_C0014484" CHECK ("EXECUTOR_TIMEOUT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_INFO" ADD CONSTRAINT "SYS_C0014485" CHECK ("EXECUTOR_FAIL_RETRY_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_INFO" ADD CONSTRAINT "SYS_C0014486" CHECK ("GLUE_TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_INFO" ADD CONSTRAINT "SYS_C0014487" CHECK ("TRIGGER_STATUS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_INFO" ADD CONSTRAINT "SYS_C0014488" CHECK ("TRIGGER_LAST_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_INFO" ADD CONSTRAINT "SYS_C0014489" CHECK ("TRIGGER_NEXT_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table XXL_JOB_LOCK
-- ----------------------------
ALTER TABLE "TEST"."XXL_JOB_LOCK" ADD CONSTRAINT "SYS_C0014515" PRIMARY KEY ("LOCK_NAME");

-- ----------------------------
-- Checks structure for table XXL_JOB_LOCK
-- ----------------------------
ALTER TABLE "TEST"."XXL_JOB_LOCK" ADD CONSTRAINT "SYS_C0014490" CHECK ("LOCK_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table XXL_JOB_LOG
-- ----------------------------
ALTER TABLE "TEST"."XXL_JOB_LOG" ADD CONSTRAINT "SYS_C0014516" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table XXL_JOB_LOG
-- ----------------------------
ALTER TABLE "TEST"."XXL_JOB_LOG" ADD CONSTRAINT "SYS_C0014491" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_LOG" ADD CONSTRAINT "SYS_C0014492" CHECK ("JOB_GROUP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_LOG" ADD CONSTRAINT "SYS_C0014493" CHECK ("JOB_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_LOG" ADD CONSTRAINT "SYS_C0014494" CHECK ("EXECUTOR_FAIL_RETRY_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_LOG" ADD CONSTRAINT "SYS_C0014495" CHECK ("TRIGGER_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_LOG" ADD CONSTRAINT "SYS_C0014496" CHECK ("HANDLE_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_LOG" ADD CONSTRAINT "SYS_C0014497" CHECK ("ALARM_STATUS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table XXL_JOB_LOG
-- ----------------------------
CREATE INDEX "TEST"."I_HANDLE_CODE"
  ON "TEST"."XXL_JOB_LOG" ("HANDLE_CODE" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "TEST"."I_TRIGGER_TIME"
  ON "TEST"."XXL_JOB_LOG" ("TRIGGER_TIME" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table XXL_JOB_LOG_REPORT
-- ----------------------------
ALTER TABLE "TEST"."XXL_JOB_LOG_REPORT" ADD CONSTRAINT "SYS_C0014517" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table XXL_JOB_LOG_REPORT
-- ----------------------------
ALTER TABLE "TEST"."XXL_JOB_LOG_REPORT" ADD CONSTRAINT "SYS_C0014498" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_LOG_REPORT" ADD CONSTRAINT "SYS_C0014499" CHECK ("RUNNING_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_LOG_REPORT" ADD CONSTRAINT "SYS_C0014500" CHECK ("SUC_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_LOG_REPORT" ADD CONSTRAINT "SYS_C0014501" CHECK ("FAIL_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table XXL_JOB_LOG_REPORT
-- ----------------------------
CREATE UNIQUE INDEX "TEST"."I_TRIGGER_DAY"
  ON "TEST"."XXL_JOB_LOG_REPORT" ("TRIGGER_DAY" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table XXL_JOB_LOGGLUE
-- ----------------------------
ALTER TABLE "TEST"."XXL_JOB_LOGGLUE" ADD CONSTRAINT "SYS_C0014518" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table XXL_JOB_LOGGLUE
-- ----------------------------
ALTER TABLE "TEST"."XXL_JOB_LOGGLUE" ADD CONSTRAINT "SYS_C0014502" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_LOGGLUE" ADD CONSTRAINT "SYS_C0014503" CHECK ("JOB_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_LOGGLUE" ADD CONSTRAINT "SYS_C0014504" CHECK ("GLUE_REMARK" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table XXL_JOB_REGISTRY
-- ----------------------------
ALTER TABLE "TEST"."XXL_JOB_REGISTRY" ADD CONSTRAINT "SYS_C0014519" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table XXL_JOB_REGISTRY
-- ----------------------------
ALTER TABLE "TEST"."XXL_JOB_REGISTRY" ADD CONSTRAINT "SYS_C0014505" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_REGISTRY" ADD CONSTRAINT "SYS_C0014506" CHECK ("REGISTRY_GROUP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_REGISTRY" ADD CONSTRAINT "SYS_C0014507" CHECK ("REGISTRY_KEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_REGISTRY" ADD CONSTRAINT "SYS_C0014508" CHECK ("REGISTRY_VALUE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table XXL_JOB_REGISTRY
-- ----------------------------
CREATE INDEX "TEST"."I_G_K_V"
  ON "TEST"."XXL_JOB_REGISTRY" ("REGISTRY_GROUP" ASC, "REGISTRY_VALUE" ASC, "REGISTRY_KEY" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table XXL_JOB_USER
-- ----------------------------
ALTER TABLE "TEST"."XXL_JOB_USER" ADD CONSTRAINT "SYS_C0014520" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table XXL_JOB_USER
-- ----------------------------
ALTER TABLE "TEST"."XXL_JOB_USER" ADD CONSTRAINT "SYS_C0014509" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_USER" ADD CONSTRAINT "SYS_C0014510" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_USER" ADD CONSTRAINT "SYS_C0014511" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TEST"."XXL_JOB_USER" ADD CONSTRAINT "SYS_C0014512" CHECK ("ROLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table XXL_JOB_USER
-- ----------------------------
CREATE UNIQUE INDEX "TEST"."I_USERNAME"
  ON "TEST"."XXL_JOB_USER" ("USERNAME" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
